# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push] # github action이 동작할 시점

jobs:
  build:

    runs-on: self-hosted # smhrd server host에 동작
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8 # OpenJDK 1.8 설치
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven # maven이용 war파일 빌드
      run: mvn -B package --file deploy/pom.xml
    - name: Publish with maven # maven활용 war파일 배포
      run: mvn tomcat7:redeploy -Dusername=admin -Dpassword=smhrd2022 --file deploy/pom.xml 
